![대체 텍스트](https://aster.cloud/wp-content/uploads/2019/10/numpy-install-cover.jpg)

![대체 텍스트](https://www.w3resource.com/w3r_images/numpy-1d2d3d-array.png)

# 1.7 Numpy
> 배열이나 행렬 연산을 할때 쓰이는 파이썬의 라이브러리

---
> library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. (reference: wiki)


In [3]:
import numpy as np                     # Numpy는 "외부 라이브러리" 이기 때문에 기능을 쓰려면 import를 먼저해야 한다. numpy를 np라는 이름을 통해 가져오라 선언하면 앞으로 넘파이가 제공하는 메서드는 np를 통해 참조 가능

x = np.array([1.0, 2.0, 4.0])        # np.array는 파이썬 list를 인수로 받아 numpy 라이브러리가 제공하는 특수한 형태의 배열(numpy.ndarray)을 반환
print(x)                 

type(x)

[1. 2. 4.]


numpy.ndarray

# 1.71 Numpy의 산술연산

* 이 예제에서는 배열 x와 y의 원소 값이 똑같다. (원소 3개를 가지는 1차원 배열)
* 원소 수가 다르면 오류가 발생
* 원소별 = element-wise / 원소별 곱셉 = element-wise product
* Numpy는 원소별 계산만 아니라 numpy 배열과 수치 하나(스칼라값)의 조합으로 된 산술 연산도 가능

In [6]:
 x = np.array([1,3,5])
 y = np.array([4,6,8])

 x + y                       # element-wise addition


array([ 5,  9, 13])

In [7]:
 x - y                       # element-wise subtaction

array([-3, -3, -3])

In [8]:
x * y                        # element-wise product

array([ 4, 18, 40])

In [9]:
x / y                        # element-wise divsion

array([0.25 , 0.5  , 0.625])

In [10]:
x / 2

array([0.5, 1.5, 2.5])

#1.72 Numpy의 N차원 배열
* 1 차원 배열 뿐만 아니라 2 차원 배열(행렬), 다차원 배열도 작성 가능

In [15]:
A = np.array([[1,3],[2,4]])       # 행렬 생성
print(A)

A.shape                           # 행렬 타입 찾는법 (2*2 Matrix)

[[1 3]
 [2 4]]


(2, 2)

In [16]:
A.dtype                          # A 행렬의 자료형 출력 (int64 / 정수형)

dtype('int64')

In [17]:
B = np.array ([[2,1],[3,5]])    # B 행렬 생성
A + B                           # matrix addition

array([[3, 4],
       [5, 9]])

In [18]:
A * B                           # matrix multiplication

array([[ 2,  3],
       [ 6, 20]])

* 수학에서 1차원 배열은 vector, 2차원 배열은 행렬이라 부르고, 또 vector와 matrix를 일반화한 것을 Tensor라고 한다.

In [19]:
print(A)

A * 10

[[1 3]
 [2 4]]


array([[10, 30],
       [20, 40]])

# 1.73 브로드캐스트

* Numpy에서 의 브로드캐스트 / Numpy Broadcasting

![대체 텍스트](https://www.astroml.org/_images/fig_broadcast_visual_1.png)

* 실제 선형대수에서의 브로트캐스트

![대체 텍스트](https://www.mathsisfun.com/algebra/images/matrix-multiply-ex1b.gif)

> 형상이 다른 배열끼리도 계산이 가능한 것을 Numpy에서는 broadcasting 기능이라 함.
> ex) [[1,2,3,4],[2,3,4,5]] + [1,2]   
> 2 by 4 matrix + 1 by 2 matrix

In [20]:
A = np.array([[2,4],[6,8]])
B = np.array([10,20])

A * B

array([[ 20,  80],
       [ 60, 160]])

# 1.74 원소 접근

In [37]:
X = np.array([[51,55], [14,19],[0,4]])
print(X)

X[0]                                        # 0행

[[51 55]
 [14 19]
 [ 0  4]]


array([51, 55])

In [38]:
X[0][1]                                     # (0,1) 위치의 원소에 접근

55

In [45]:
for row in X:                               # for(반복문으로 구현 가능) 
  print(row)

51
55
14
19
0
4


In [44]:
X = X.flatten()                             # X를 1차원 배열로 변환(평탄화)
print(X)

X[np.array([0,2,4])]                        # 인덱스가 0,2,4인 원소 얻기

[51 55 14 19  0  4]


array([51, 14,  0])